# -*- coding: utf-8 -*-
"""Hurdat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RnJJyxycrVarRx4EBeF1ASYT-D6_W6mL
"""

import pandas as pd
import numpy as np
from google.colab import files
url='https://raw.githubusercontent.com/nicolascarva/HURDAT/main/hurdat2-1851-2019-052520.csv'

"""###Data consists of one row with information identifying hurricane (Primary Row) and subsequent rows with information known about the hurricane at specific date &  time (Data Rows) - up until the next row with information identifying hurricane"""

df=pd.read_csv(url, names=['id', 'time', 'record_identifier','status','latitude','longitude','max_sust_wind', 'min_press',])
df.head(30)

"""###We'll add a column with the hurricane id and name concatenated, this will be our unique identifier; we'll fill all subsequent rows with the same identifier (id-name). We'll also add a column to tag data rows to be dropped later."""

#Add Unique identifier (id-name) column
df['id-name']=(df['id']*df['max_sust_wind'].isnull()+df['max_sust_wind'].isnull()*df['time'])

df.loc[(df['id-name']==''),'id-name']=np.NaN #Set Data Rows in id-name columns as NaN to be filled in subsequent step
df.loc[(df['min_press']==-999, 'min_press')]=np.NaN #Set unknown minimum pressure as NaN
u_hur_=df['id-name'].value_counts().sum()
print(u_hur_)

df['drop_']=df['id-name'] # Add column to tag rows to be dropped later
df['id-name'].fillna(method='ffill',inplace=True) #Fill id-name column
pd.set_option('display.max_rows', 200)
# df.tail(100)

#Adding lf column if storm makes landfall (1 for landfall, 0 for no landfall)
for i in range (len(df)):
  df['record_identifier'][i]=df['record_identifier'][i].strip()

df.loc[df['record_identifier']=='L',['lf']]=1 #Tag hurricanes that made landfall with a 1 (to be grouped later)
df.loc[df['record_identifier']!='L',['lf']]=0
# df.head(100)

# Set unique identifier as index
# df.set_index(df['id-name'], inplace=True)

#Calculate Number of Hurricanes and check
total_hur=df['id-name'].nunique()
total_hur
assert total_hur==u_hur_
total_hur
list_hur=df['id-name'].unique().tolist()

#Create dataframe with max wind speed, mean wind speed, minimum pressure, mean pressure, landfall status,  of each hurricane
max_speed=df.groupby(['id-name'], sort=None)['max_sust_wind'].max()
max_speed=pd.DataFrame(max_speed)
max_speed.reset_index(inplace=True)
max_speed.rename(columns={"max_sust_wind": "max_wind"}, inplace=True)
# print('Max Speed reached: ', max_speed)
# max_speed.head()

mean_speed=df.groupby(['id-name'], sort=None)['max_sust_wind'].mean()
mean_speed=pd.DataFrame(mean_speed)
mean_speed.reset_index(inplace=True)
mean_speed.rename(columns={"max_sust_wind": "mean_wind"}, inplace=True)
# print('Mean of Maximum Speed: ', mean_speed)

min_pressure=df.groupby(['id-name'], sort=None)['min_press'].min()
min_pressure=pd.DataFrame(min_pressure)
min_pressure.reset_index(inplace=True)
# print('Minimum Pressure reached: ', min_pressure)

mean_pressure=df.groupby(['id-name'], sort=None)['min_press'].mean()
mean_pressure=pd.DataFrame(mean_pressure)
mean_pressure.reset_index(inplace=True)
mean_pressure.rename(columns={"min_press": "mean_of_min_press"}, inplace=True)
# print('Mean of Minimum Pressure: ', mean_pressure)

lf=df.groupby(['id-name'], sort=None)['lf'].max()
lf=pd.DataFrame(lf)
lf.reset_index(inplace=True)
# print('Landfall status: ', lf)
# lf.head()

#drop rows to keep unique hurricanes
df_hur=df.dropna(subset=['drop_'])
df_hur.drop(columns=['status','latitude','longitude', 'drop_', 'record_identifier','max_sust_wind',	'min_press', 'lf'], inplace=True)
df_hur.head(25)
df_hur.rename(columns={"time": "Name"}, inplace=True)
df_hur.head(20)

#Add year column
df_hur['year']=df_hur['id'].str[-4:]
df_hur.reset_index() 
df_hur.head() #Add year column

#Add max speed column
df_hur=pd.merge(df_hur, max_speed, on=['id-name'])
df_hur.head()
# Add mean wind column
df_hur=pd.merge(df_hur, mean_speed, on=['id-name'])
df_hur.head()
#Add min press column
df_hur=pd.merge(df_hur, min_pressure, on=['id-name'])
df_hur.head(10)
#Add mean press column
df_hur=pd.merge(df_hur, mean_pressure, on=['id-name'])
df_hur.head(25)
#Add lf column
df_hur=pd.merge(df_hur, lf, on=['id-name'])
df_hur.head(15)

#Group data by years 
max_wind_year=df_hur.groupby(['year'], sort=None)['max_wind'].max()

min_press_year=df_hur.groupby(['year'], sort=None)['min_press'].min()

num_hur_year=df_hur['year'].value_counts()

lf_year=df_hur.groupby(['year'],sort=None)['lf'].sum()


# unique_years=df_hur['year'].unique()
# unique_years
df_year=pd.DataFrame({'year': df_hur['year'].unique(), 'max_wind': max_wind_year, 'min_press': min_press_year, 'No_of_Hurricanes': num_hur_year, 'No_of_lf_Hurricanes': lf_year})

df_year['lf_perc']=df_year['No_of_lf_Hurricanes']/df_year['No_of_Hurricanes']*100
df_year.head(10)

if df_year['year'].dtype=='O':
  df_year['year'] = pd.DatetimeIndex(pd.to_datetime(df_year['year'])).year #Change year format to integer
print(df_year['year'][3].dtype)
df_year.head()
# df_year['year'].dtypes

import matplotlib.pyplot as plt

plt.scatter(df_year['year'], df_year['No_of_Hurricanes'], )

df.loc[df['year'].between(1975,1980)].head()

from statsmodels.formula.api import ols
model=ols('lf_perc ~ year', data=df_year).fit()
print(model.summary())

from statsmodels.formula.api import ols
model=ols('max_wind ~ year', data=df_year).fit()
print(model.summary())

from statsmodels.formula.api import ols
model=ols('No_of_Hurricanes ~ year', data=df_year).fit()
print(model.summary())

from statsmodels.formula.api import ols
model=ols('max_wind ~ year', data=df_year).fit()
print(model.summary())